/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spirit;

import controle.Bilan;
import controle.BilanControler;
import datamanager.outils.BilanObservateur;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author genius
 */
public class PanneauBilan extends javax.swing.JPanel implements BilanObservateur{

    BilanControler controler;
    /**
     * Creates new form PanneauBilan
     */
    public PanneauBilan() {
        initComponents();
        configure();
    }
    
    void configure(){
        Date date = new Date();
        int anMax = date.getYear()+1900,
        j = date.getDate(),
        m = date.getMonth()+1;
        int  i = 0;
        for(i=2018;i<=anMax;i++){
            annee.addItem(String.valueOf(i));
        }
        
        controler = new BilanControler();
        controler.setObserteur(this);
        
        mois.setSelectedIndex(m);
        jour.setSelectedIndex(j);
        annee.setSelectedIndex(i-2018-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel25 = new javax.swing.JPanel();
        filtre = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jour = new javax.swing.JComboBox<>();
        mois = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        annee = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        bilan = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel25.setBackground(new java.awt.Color(228, 234, 240));
        jPanel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 204, 204), null, null));

        filtre.setText("Chercher");
        filtre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtreActionPerformed(evt);
            }
        });

        jButton2.setText("Exporter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jour.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jourItemStateChanged(evt);
            }
        });

        mois.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        mois.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                moisItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setText("Date   :");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Année");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setText("Mois");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel4.setText("Jour ");

        annee.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                anneeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filtre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jour, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mois, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(annee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel25, java.awt.BorderLayout.PAGE_START);

        bilan.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        bilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Designation", "Prix unitaire", "nombre vendus", "Total vendu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bilan.setRowHeight(30);
        jScrollPane1.setViewportView(bilan);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        controler.exportBilan();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void anneeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_anneeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_anneeItemStateChanged

    private void filtreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtreActionPerformed
            if (!mois.getSelectedItem().toString().equals("0")) {
                if (!jour.getSelectedItem().toString().equals("0")) {
                    System.out.println(jour.getSelectedItem());
                    controler.findByDay(Integer.parseInt(jour.getSelectedItem().toString())
                                       ,Integer.parseInt(mois.getSelectedItem().toString()) ,
                                       Integer.parseInt(annee.getSelectedItem().toString()));
                }else{
                    controler.findByMonth(Integer.parseInt(mois.getSelectedItem().toString()) ,
                                          Integer.parseInt(annee.getSelectedItem().toString()));
                }
            }else{
                controler.findByYear(Integer.parseInt(annee.getSelectedItem().toString()));
            }
    }//GEN-LAST:event_filtreActionPerformed

    private void moisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_moisItemStateChanged

    }//GEN-LAST:event_moisItemStateChanged

    private void jourItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jourItemStateChanged

    }//GEN-LAST:event_jourItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> annee;
    private javax.swing.JTable bilan;
    private javax.swing.JButton filtre;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jour;
    private javax.swing.JComboBox<String> mois;
    // End of variables declaration//GEN-END:variables

    @Override
    public void upadateBilan(ArrayList<Bilan> pList) {
        ((DefaultTableModel)bilan.getModel()).setRowCount(0);
        
        System.out.println(pList.size());
        
        pList.forEach((bil) -> {
            ((DefaultTableModel)bilan.getModel()).addRow(new Object[]{
                bil.getDesignation(),
                bil.getPrix(),
                bil.getNbvente(),
                bil.getTotale()
            });
        });
    }
    

}
