/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spirit;

import controle.StockContoler;
import datamanager.outils.SConnection;
import datamanager.outils.StockObservateur;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import spirit.entites.Approvisionnement;

/**
 *
 * @author genius
 */
public class PanneauApprovisionnement extends javax.swing.JPanel implements StockObservateur{

    private StockContoler contoler;
    /**
     * Creates new form PanneauApprovisionnement
     */
    public PanneauApprovisionnement() {
        initComponents();
        configure();
        initYearCombo();
    }
    
    public void configure(){
        
        contoler = new StockContoler(SConnection.getConnection());
        contoler.setObservateur(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeApp = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        myChooser = new com.toedter.calendar.JMonthChooser();
        yearComb = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(236, 238, 241));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(7, 7, 7, 7));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/refresh.png"))); // NOI18N
        jButton1.setText("Rafraichir");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        listeApp.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        listeApp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produit", "Date approvisionnement", "Quantité ajouter"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listeApp.setGridColor(new java.awt.Color(0, 0, 0));
        listeApp.setRowHeight(30);
        listeApp.setSelectionBackground(new java.awt.Color(5, 243, 170));
        listeApp.setShowHorizontalLines(true);
        listeApp.setShowVerticalLines(true);
        listeApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeAppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeApp);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Filtrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel1.setText("Historique des approvisionnements");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yearComb, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(myChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yearComb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateAppr(contoler.getManager().findAll());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listeAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeAppMouseClicked

    }//GEN-LAST:event_listeAppMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               int mois = myChooser.getMonth()+1;
               
               contoler.filtre(mois,Integer.parseInt(yearComb.getSelectedItem().toString()));
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void initYearCombo(){
        
        int max = new Date().getYear()+1900;
        
        for (int i = 2018; i <= max; i++) {
            yearComb.addItem(String.valueOf(i));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable listeApp;
    private com.toedter.calendar.JMonthChooser myChooser;
    private javax.swing.JComboBox<String> yearComb;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateAppr(ArrayList<Approvisionnement> liste) {
//        DefaultTableModel model =  ((DefaultTableModel)listeApp.getModel());
//        model.setRowCount(0);
//        
//        for (Approvisionnement app : liste) {
//            model.addRow(new Object[]{
//                
//                //app.getProduit().getDesignation(),
//                app,
//                Math.round(app.getQuantite())
//                
//            });
//        }
    }
}
